package ru.task.snapengageEndpoint.utils;
/**
 * Created by bumurzaqov on 28.04.2018.
 */
public class SampleJson {

    public static final String FULL_REQUEST_SAMPLE =
            "{" + "    \"id\": \"8b7c3b3b-f5d7-4e58-96d8\","
                    + "    \"widget_id\": \"e8175843-d381-4d7c-aa9f-0da1610ad1b\","
                    + "    \"url\": \"https://www.snapengage.com/viewcase?c=8b7c3b3b-f5d7-4e58-96d8\","
                    + "    \"snapshot_image_url\": \"https://www.snapengage.com/snapabug/ServiceImage?c=8b7c3b3b-f5d7-4e58-96d8\","
                    + "    \"type\": \"chat\","
                    + "    \"requested_by\": \"test@test.com\","
                    + "    \"requester_details\":"
                    + "      {"
                    + "        \"name\": \"Jim Tester\","
                    + "        \"emails\": [\"test@example.com\"],"
                    + "        \"name_profile_link\": \"http://facebook.com/jimtester\","
                    + "        \"phones\": [\"555-555-1010\"],"
                    + "        \"address\": \"111 2nd Ave.\","
                    + "        \"address_2\": \"\","
                    + "        \"city\": \"Boulder\","
                    + "        \"state\": \"CO\","
                    + "        \"zip\": \"80303\","
                    + "        \"country\": \"US\","
                    + "        \"company_name\": \"SnapEngage\","
                    + "        \"company_profile_link\": \"http://facebook.com/snapengage\","
                    + "        \"employees\": \"Abe,Betty,Charlie\"," + "        \"revenue\": \"100\","
                    + "        \"title\": \"CEO\","
                    + "        \"website\": \"www.snapengage.com\","
                    + "        \"social_profile_links\": [\"www.facebook.com/jimatsnapengage\",\"www.twitter.com/jimtesteratsnap\"],"
                    + "        \"gender\": \"Male\","
                    + "        \"age\": 44,"
                    + "        \"influencer_score\": \"88.8\","
                    + "        \"notes\": \"This is just for testing\","
                    + "        \"industry\": \"Tech\","
                    + "        \"avatars\": [\"http://www.avatars.com/jimtester\"],"
                    + "        \"other_data\": []"
                    + "      },"
                    + "    \"description\": \"Testing the Open API...\","
                    + "    \"created_at_date\": \"Oct 3, 2014 2:14:31 PM\","
                    + "    \"created_at_seconds\": 1412367271,"
                    + "    \"created_at_milliseconds\": 268,"
                    + "    \"proactive_chat\": false,"
                    + "    \"page_url\": \"http://www.snapengage.com/demo/postapi.html\","
                    + "    \"referrer_url\": \"http://www.comingfromurl.com\","
                    + "    \"entry_url\": \"http://www.yoursite.com\","
                    + "    \"ip_address\": \"67.174.108.196\","
                    + "    \"user_agent\": \"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/3.0.195.27 Safari/532.0,gzip(gfe)\","
                    + "    \"browser\": \"Chrome (3.0.195.27)\","
                    + "    \"os\": \"Microsoft Windows Vista\","
                    + "    \"country_code\": \"US\","
                    + "    \"country\": \"United States\","
                    + "    \"region\": \"16\","
                    + "    \"city\": \"Boulder\","
                    + "    \"latitude\": 39.914700,"
                    + "    \"longitude\": -105.080902,"
                    + "    \"source_id\": 2,"
                    + "    \"chat_waittime\": 2,"
                    + "    \"chat_duration\": 15,"
                    + "    \"language_code\": \"en-US,en;q=0.8\","
                    + "    \"transcripts\": ["
                    + "      {"
                    + "        \"id\": \"visitor@test.com\","
                    + "        \"date\": \"Oct 3, 2014 2:14:31 PM\","
                    + "        \"date_seconds\": 1412367271,"
                    + "        \"date_milliseconds\": 154,"
                    + "        \"alias\": \"visitor\","
                    + "        \"message\": \"Hello, \""
                    + "      },"
                    + "      {"
                    + "        \"id\": \"jerome@snapengage.com\","
                    + "        \"date\": \"Oct 3, 2014 2:14:31 PM\","
                    + "        \"date_seconds\": 1412367271,"
                    + "        \"date_milliseconds\": 456,"
                    + "        \"alias\": \"test\","
                    + "        \"message\": \"Hi, \""
                    + "      },"
                    + "      {"
                    + "        \"id\": \"vistor@test.com\","
                    + "        \"date\": \"Oct 3, 2014 2:14:31 PM\","
                    + "        \"date_seconds\": 1412367271,"
                    + "        \"date_milliseconds\": 835,"
                    + "        \"alias\": \"visitor\","
                    + "        \"message\": \"This is a test.\""
                    + "      }"
                    + "    ],"
                    + "    \"plugins\": ["
                    + "      {"
                    + "        \"name\": \"Java\","
                    + "        \"value\": \"1.2.3\""
                    + "      }, {"
                    + "        \"name\": \"Flash\","
                    + "        \"value\": \"3.4.5\""
                    + "    }],"
                    + "    \"javascript_variables\": [{"
                    + "        \"name\": \"variable1\","
                    + "        \"value\": \"v1_1234\""
                    + "    }, {"
                    + "        \"name\": \"variable2\","
                    + "        \"value\": \"v2_123456789\""
                    + "    }],"
                    + "    \"operator_variables\": [{"
                    + "        \"name\": \"note\","
                    + "        \"value\": \"this is a note entered by the agent\""
                    + "    }, {"
                    + "        \"name\": \"customerTemp\","
                    + "        \"value\": \"Very Happy\""
                    + "    }]"
                    + "}";

}
